channels:
  - damianavila82
  - conda-forge
dependencies:
  - python=3.6.5
  - numpy=1.14.5
  - matplotlib=2.2.2
  - pandas=0.23.1
  - rise=5.3.0
  - ipywidgets=7.2.1
  - scikit-learn=0.19.1
  - matplotlib-venn=0.11.5
  - pip:
    - jupyter-contrib-nbextensions